title: "&7[&lTITLE&r&7]"
# 界面
# auto 自动适配
# packet 箱子界面
# ui From窗口
UI: auto
#mysql

empty-display: "无称号"


# 数据库配置信息
# 如果你希望称号支持跨服功能 则需要启用数据库
mysql:
  enable: false
  host: "localhost"
  port: 3306
  user: "ganq2333"
  password: "ganq2333"
  database: "title"